### ISSUE TITLE
Refactor to use Provider

### ISSUE THREAD

**Issue by Joel-Groves** [MufasaTheMusician/eatwithme#18] opened 2019-07-31 08:49 UTC
-Centralised location for streams

**Comment by MufasaTheMusician** [comment] 2019-08-07 16:03
- Map and card profiles done, but need to verify it works on iOS as well.
- Chat room list done.
- Working on chat room (with message bubbles), close to halfway
- Last part will be the EditProfile section

**Comment by MufasaTheMusician** [comment] 2019-08-08 11:00
Duplicate of #39

**Closed by MufasaTheMusician** 2019-08-08 11:00 UTC
